### PR TITLE
Support scrypt kdf with non-default params

### PR DESCRIPTION
**Pull request by charleso**
! @erikd-ambiata @olorin 
/jury approved @olorin

### CODE REVIEW

**Comment by erikd-ambiata** [comment]
Code seems fine, but I seem to be missing some context on this.

Where is will this be called from? Looking at that rest of the code, it looks like it would be possible to do something like `scryptParams 1 1 1` which would almost certainly result in very poor crypto properties. Is it worth guarding against this?

**Comment by erikd-ambiata** [comment]
Context explained IRL.

**Comment by olorin** [comment]
I'm not sure this is the right way to do this. One of the goals of tinfoil is to present a simple, unified interface with the properties that a) there is an obvious way to do everything that tinfoil can do and b) the obvious way is also the correct way (aka, make it really hard to shoot yourself in the foot). As I understand it, the motivation for this change is to be able to use two different workfactors for different applications with differing requirements; if this is the case I think the right way to expose this in tinfoil is to have two different KDF instances, {high,low}WorkFactorScrypt or something like that.

**Comment by olorin** [comment]
(Separately from the interface issue, this implementation incorrectly uses the same MCF prefix as `defaultScrypt`, which will result in verification failures when the resulting KDF instance is used.)

**Comment by olorin** [comment]
Sorry we didn't get a chance to catch up when planned @charleso. Free whenever you are.

**Comment by olorin** [comment]
👍

**Pull request merged**
