### PR TITLE
Add boris config

### PR DESCRIPTION
**Pull request by olorin**
Cargo-culted from `p`, not sure if there's anything else I need to do here.

@nhibberd @markhibberd

### CODE REVIEW

**Comment by nhibberd** [comment]
Yup this looks good 👍

**Comment by nhibberd** [comment]
Only thing to say actually is, are you sure you want 8.0 builds? (never had them before)

**Comment by olorin** [comment]
> Only thing to say actually is, are you sure you want 8.0 builds? (never had them before)

Just figured this was as good a time as any to support them, not necessary for now but doesn't hurt either.

**Comment by tmcgilchrist** [comment]
Disorder, p and x all support 8.0 @olorin

**Comment by olorin** [comment]
> Disorder, p and x all support 8.0 @olorin

\o/

**Comment by markhibberd** [comment]
👍 I am good with this when it is green, but it may be better to do in two PRs. Just push boris-git.toml in one PR, this will allow branch builds to happen so you can test get it green before you merge.

**Comment by olorin** [comment]
> :+1: I am good with this when it is green, but it may be better to do in two PRs. Just push boris-git.toml in one PR, this will allow branch builds to happen so you can test get it green before you merge.

Can do, rebased for the first one.

**Pull request merged**
