### PR TITLE
Widen semigroups bounds

### PR DESCRIPTION
**Pull request by charleso**
/cc @olorin @nhibberd 

Same as p

### CODE REVIEW

**Comment by erikd-ambiata** [comment]
:sake:

**Comment by tmcgilchrist** [comment]
🔨

**Comment by olorin** [comment]
@charleso this change is okay, but I'm concerned about "something's broken" -> "push fix and quickly merge" becoming common - it's fine in a lot of codebases, but isn't appropriate for `tinfoil`. Guessing you didn't see this, but it's mentioned in the [readme](https://github.com/ambiata/tinfoil/commit/c80a16e5ff871f373fb98e66809f669360741dfb#diff-04c6e90faac2675aa89e2176d2eec7d8R13) that all changes need to be approved by both me and @markhibberd before being merged due to the potentially-catastrophic consequences of subtle breakages. Like I said, no problems with this change but in the future please get signoff from me and Mark before merging - feel free to ping on hipchat or call me if it's urgent.

**Comment by charleso** [comment]
@olorin My sincere apologies, it wasn't urgent. I have already seen the README so there's no excuse. Will happily wait next time.

**Comment by olorin** [comment]
@charleso no dramas, thanks. :+1:

**Pull request merged**
