### PR TITLE
Upgrade world

### PR DESCRIPTION
**Pull request by thumphries**
P exports deepseq and ($!) now

### CODE REVIEW

**Comment by olorin** [comment]
Missing some context here, why are we upgrading the world?

**Comment by thumphries** [comment]
I was upgrading napoleon, it pulled tinfoil, the build failed for bytestring reasons

**Comment by olorin** [comment]
Looks fine to me. :+1:, but wait for a :shaved_ice: from @markhibberd as well.

**Comment by thumphries** [comment]
@markhibberd ran into this one again just now, any problems with bytestring bounds?

**Comment by markhibberd** [comment]
:+1:

**Pull request merged**
