### PR TITLE
Replace massive libsodium subtree with a submodule

### PR DESCRIPTION
**Pull request by olorin**
Forked to ambiata/libsodium and created an `ambiata` branch from the
tag 1.0.11, then applied the autoconf patch from 547d0e1.

The reason I used a subtree initially was I found with `scrypt` that
it made it simpler to review/patch library code, but I have been
convinced that the negatives outweigh the positives in this case
(`libsodium` is massive, we really want to avoid patching it if we can
possibly avoid it, and it's consistent with how we solve this problem
elsewhere).

! @erikd-ambiata @thumphries @charleso

### CODE REVIEW

**Comment by thumphries** [comment]
🏌️

**Comment by erikd-ambiata** [comment]
> +4 −107,734

:trophy:

**Comment by charleso** [comment]
Just to confirm we didn't make any changes to the source that would need to be kept/applied to the fork?

**Comment by olorin** [comment]
> Just to confirm we didn't make any changes to the source that would need to be kept/applied to the fork?

We did, [this commit](https://github.com/ambiata/libsodium/commit/e2d6cefcb581505077e49a007cc57ac996e2c729) on the `ambiata` branch of the libsodium fork should match [this commit](https://github.com/ambiata/tinfoil/commit/547d0e161742daaf7e4a7c5e9bb295fb04f73702) in `tinfoil`. It was done with a `git show -p` + `git apply`, the only changes are the commit message and the path prefix (lib/libsodium in tinfoil, / in libsodium fork).

Look okay?

**Comment by olorin** [comment]
(To clarify, not actually a change to the source, just committing autogenerated code because we can't generate it on ancient-centos.)

**Comment by charleso** [comment]
👍

**Pull request merged**
