### PR TITLE
Rename lock files to correct name to match cabal definition

### PR DESCRIPTION
**Pull request by nhibberd**
@markhibberd @olorin @jystic 

Mafia will use the cabal project name to find lock files by default, in this case [ambiata-tinfoil](https://github.com/ambiata/tinfoil/blob/master/ambiata-tinfoil.cabal#L1)

### CODE REVIEW

**Comment by jystic** [comment]
👍 on 🍏

**Comment by markhibberd** [comment]
👍

**Comment by olorin** [comment]
:+1:, but please be careful making changes here - see https://github.com/ambiata/tinfoil/pull/41#issuecomment-224188899 for the reasoning for the double-signoff requirement in the readme.

**Comment by jystic** [comment]
@olorin maybe this should be locked down like butter?

**Comment by olorin** [comment]
> @olorin maybe this should be locked down like butter? 

Yeah agreed, if we keep the policy it'd be good to have a technical reminder behind it, too easy for people to overlook otherwise. Not critical in the same way ops repos are, but still useful (I think @markhibberd had a plan to do this at some point).

**Pull request merged**
